

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

// Self-contained type to avoid import issues in Vercel serverless environment
enum BotLanguage {
  MQL4 = 'MQL4',
  MQL5 = 'MQL5',
}

const getResponseText = (response: GenerateContentResponse): string => {
    return response.text;
};

const getBotPrompt = (description: string, language: BotLanguage) => `You are an expert MQL developer. Your task is to generate the code for a trading bot (Expert Advisor) based on the user's description.
- Language: ${language}
- User Description of desired behavior: "${description}"
IMPORTANT: At the very top of the generated code, you MUST include the following MQL properties:
#property copyright "Generated by Grey Algo Apex Trader"
#property link      "https://greyalgo-trading.netlify.app"
#property description "Also visit Quant Systems Trading: https://quant-systems-trading.netlify.app"
After these properties, generate the complete, functional, and well-commented ${language} code. The code must be ready to be compiled in MetaEditor. Respond with ONLY the raw code, without any surrounding text, explanations, or markdown code blocks.`;

export default async function handler(req: VercelRequest, res: VercelResponse) {
    if (req.method !== 'POST') {
        return res.status(405).json({ success: false, message: 'Method not allowed' });
    }
    
    if (!process.env.API_KEY) {
        return res.status(500).json({ success: false, message: 'API key not configured' });
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
        const { description, language } = req.body;

        if (!description || !language) {
            return res.status(400).json({ success: false, message: 'Missing description or language' });
        }

        const prompt = getBotPrompt(description, language as BotLanguage);
        const response = await ai.models.generateContent({ model: 'gemini-2.5-flash', contents: prompt });
        const code = getResponseText(response);
        
        return res.status(200).json({ success: true, code });

    } catch (error: any) {
        console.error("Error in /api/createBot:", error);
        return res.status(500).json({ success: false, message: error.message || 'Internal server error' });
    }
}
